/**
 * Thread Calculator Options & Preset Constants
 */

export const CALCULATOR_STANDARDS = [
  {
    id: "metric",
    label: "ISO Metric (M / MF)",
    angle: 60,
    unit: "mm",
    classesExt: [
      { id: "6g", label: "6g (Standard Medium Fit)" },
      { id: "4g6g", label: "4g6g (Precision Fine Fit)" },
      { id: "6e", label: "6e (Large Allowance Fit)" },
      { id: "6h", label: "6h (Zero Allowance Fit)" },
      { id: "8g", label: "8g (Coarse Loose Fit)" },
    ],
    classesInt: [
      { id: "6H", label: "6H (Standard Medium Fit)" },
      { id: "5H", label: "5H (Precision Fine Fit)" },
      { id: "7H", label: "7H (Coarse Fit)" },
      { id: "6G", label: "6G (Large Allowance Fit)" },
    ],
  },
  {
    id: "un",
    label: "Unified Inch (UNC / UNF / UNEF)",
    angle: 60,
    unit: "inch",
    classesExt: [
      { id: "2A", label: "Class 2A (Standard Fit)" },
      { id: "3A", label: "Class 3A (Close Tight Fit)" },
      { id: "1A", label: "Class 1A (Loose Fit)" },
    ],
    classesInt: [
      { id: "2B", label: "Class 2B (Standard Fit)" },
      { id: "3B", label: "Class 3B (Close Tight Fit)" },
      { id: "1B", label: "Class 1B (Loose Fit)" },
    ],
  },
  {
    id: "bsw",
    label: "British Standard Whitworth (BSW / BSF)",
    angle: 55,
    unit: "inch",
    classesExt: [
      { id: "Medium", label: "Medium Fit (Standard)" },
      { id: "Close", label: "Close Fit (Precision)" },
      { id: "Free", label: "Free Fit (Commercial)" },
    ],
    classesInt: [
      { id: "Medium", label: "Medium Fit (Standard)" },
      { id: "Close", label: "Close Fit (Precision)" },
      { id: "Free", label: "Free Fit (Commercial)" },
    ],
  },
  {
    id: "bsp",
    label: "BSP Parallel Pipe (BSPP / G)",
    angle: 55,
    unit: "mm",
    classesExt: [
      { id: "Class A", label: "Class A (Standard)" },
      { id: "Class B", label: "Class B (Wider Tolerance)" },
    ],
    classesInt: [{ id: "Standard", label: "Standard Internal" }],
  },
  {
    id: "npt",
    label: "National Pipe Taper (NPT)",
    angle: 60,
    unit: "inch",
    classesExt: [{ id: "Standard", label: "ASME B1.20.1 Standard" }],
    classesInt: [{ id: "Standard", label: "ASME B1.20.1 Standard" }],
  },
  {
    id: "acme",
    label: "Acme Thread (29° ASME B1.5)",
    angle: 29,
    unit: "inch",
    classesExt: [
      { id: "2G", label: "2G General Purpose (Standard)" },
      { id: "3G", label: "3G Close Fit" },
      { id: "4G", label: "4G Precision Fit" },
    ],
    classesInt: [
      { id: "2G", label: "2G General Purpose (Standard)" },
      { id: "3G", label: "3G Close Fit" },
      { id: "4G", label: "4G Precision Fit" },
    ],
  },
  {
    id: "trapezoidal",
    label: "Metric Trapezoidal (Tr - DIN 103)",
    angle: 30,
    unit: "mm",
    classesExt: [
      { id: "7e", label: "7e Medium Clearance" },
      { id: "7h", label: "7h Zero Clearance" },
    ],
    classesInt: [{ id: "7H", label: "7H Standard Internal" }],
  },
  {
    id: "custom",
    label: "Custom Thread Calculator",
    angle: 60,
    unit: "mm",
    classesExt: [{ id: "custom", label: "Custom Calculated Fit" }],
    classesInt: [{ id: "custom", label: "Custom Calculated Fit" }],
  },
];

export const ACME_TRAPEZOIDAL_PRESETS = [
  {
    id: "acme_0_5",
    size: "1/2 - 10 ACME",
    basicMajor: "0.500 in (12.70 mm)",
    basicPitch: "0.450 in (11.43 mm)",
    basicMinor: "0.400 in (10.16 mm)",
    pitch: "0.1000 in (2.540 mm)",
    tpi: "10",
    angle: "29°",
    height: "0.0500 in (1.27 mm)",
    tapDrill: "0.400 in (10.16 mm)",
    clearanceDrill: "0.531 in (13.49 mm)",
    external: {
      major: { min: "0.490", max: "0.500" },
      pitch: { min: "0.443", max: "0.450" },
      minor: { min: "0.388", max: "0.400" },
      class: "2G",
    },
    internal: {
      major: { min: "0.500", max: "0.520" },
      pitch: { min: "0.450", max: "0.458" },
      minor: { min: "0.400", max: "0.412" },
      class: "2G",
    },
  },
  {
    id: "acme_0_75",
    size: "3/4 - 6 ACME",
    basicMajor: "0.750 in (19.05 mm)",
    basicPitch: "0.667 in (16.93 mm)",
    basicMinor: "0.583 in (14.82 mm)",
    pitch: "0.1667 in (4.233 mm)",
    tpi: "6",
    angle: "29°",
    height: "0.0833 in (2.12 mm)",
    tapDrill: "0.583 in (14.82 mm)",
    clearanceDrill: "0.781 in (19.84 mm)",
    external: {
      major: { min: "0.738", max: "0.750" },
      pitch: { min: "0.658", max: "0.667" },
      minor: { min: "0.570", max: "0.583" },
      class: "2G",
    },
    internal: {
      major: { min: "0.750", max: "0.775" },
      pitch: { min: "0.667", max: "0.677" },
      minor: { min: "0.583", max: "0.598" },
      class: "2G",
    },
  },
  {
    id: "tr_16_4",
    size: "Tr 16 × 4",
    basicMajor: "16.000 mm",
    basicPitch: "14.000 mm",
    basicMinor: "12.000 mm",
    pitch: "4.000 mm",
    tpi: "6.35",
    angle: "30°",
    height: "2.000 mm",
    tapDrill: "12.00 mm",
    clearanceDrill: "17.00 mm",
    external: {
      major: { min: "15.700", max: "16.000" },
      pitch: { min: "13.780", max: "13.950" },
      minor: { min: "11.600", max: "11.950" },
      class: "7e",
    },
    internal: {
      major: { min: "16.000", max: "16.500" },
      pitch: { min: "14.000", max: "14.250" },
      minor: { min: "12.000", max: "12.350" },
      class: "7H",
    },
  },
  {
    id: "tr_20_4",
    size: "Tr 20 × 4",
    basicMajor: "20.000 mm",
    basicPitch: "18.000 mm",
    basicMinor: "16.000 mm",
    pitch: "4.000 mm",
    tpi: "6.35",
    angle: "30°",
    height: "2.000 mm",
    tapDrill: "16.00 mm",
    clearanceDrill: "21.00 mm",
    external: {
      major: { min: "19.700", max: "20.000" },
      pitch: { min: "17.780", max: "17.950" },
      minor: { min: "15.600", max: "15.950" },
      class: "7e",
    },
    internal: {
      major: { min: "20.000", max: "20.500" },
      pitch: { min: "18.000", max: "18.250" },
      minor: { min: "16.000", max: "16.350" },
      class: "7H",
    },
  },
];
